# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging by setting to 'colorlog' -- if set to 'none', logging will not
# be modified by hydra (i.e. then the logging config from the code will be used)
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${project_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}_${nodename_bigram:}
sweep:
  dir: ${paths.log_dir}/${project_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
