name: Unit tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: jobirk/omnijet:latest
    steps:
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: bash -c "source /opt/conda/bin/activate && export PYTHONPATH=$PWD:$PYTHONPATH && pytest"
